spring.application.name=DonaTrack_Logistica.java
spring.datasource.url=jdbc:mysql://localhost:3306/Logistica_DB?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true